### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [asarkar/jwsur2#1]
Hi
The following lines have cryptographic API misuses. <br> File name => jwsur2-ch5/src/main/java/com/github/mkalin/jwsur2/ch5/predictions/ServiceHashHandler.java: Line number => 97: API name => SecretKeySpec:<BR> File name => jwsur2-ch5/src/main/java/com/github/mkalin/jwsur2/ch5/predictions/ServiceHashHandler.java: Line number => 97: API name => SecretKeySpec:<BR> File name => jwsur2-ch6/src/main/java/com/github/mkalin/jwsur2/ch6/predictions/https/client/PredictionsHttpsClientAA.java: Line number => 30: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => jwsur2-ch6/src/main/java/com/github/mkalin/jwsur2/ch6/predictions/https/client/PredictionsHttpsClient.java: Line number => 29: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by asarkar** [comment]
Bot.
